unstable_features = true
max_width=300
chain_width=250
single_line_if_else=true
fn_call_width = 100
impl_empty_single_line = true
fn_empty_single_line = false
fn_single_line = true
struct_lit_single_line = true
struct_lit_width = 300


