[package]
name = "ewin"
version = "0.1.0"
authors = ["hi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
termion = "1.5.5"
clap = "2"
unicode-width = "0"
clipboard = "0.5.0"
crossterm  = "0.17.8" 
serde = { version = "1.0.115", features = ["derive"] }
toml = "0.5.6"
signal-hook = "0.1"
