[package]
name = "ewin"
version = "0.8.0"
description = "Simple editor for Window(GUI) users.No need to remember commands."
authors = ["thinkingreed"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/thinkingreed/ewin"
license = "MIT"
keywords = ["text", "editor", "terminal", "cli", "tui"]
categories = ["command-line-utilities"]
build = "build.rs"

[profile.dev]
debug = 0

[package.metadata.deb]
extended-description = """\
Simple editor for Window(GUI) users.\ 
No need to learn new commands.\

It provides basic features as a minimal text editor.\
depends = "$auto"\
"""
assets = [
    ["target/release/ewin", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/ewin/README", "644"],
]

[package.metadata.rpm]
package = "ewin"
[package.metadata.rpm.cargo]
buildflags = ["--release"]
[package.metadata.rpm.targets]
ewin = { path = "/usr/bin/ewin" }

[dependencies]
anyhow = "1"
clap = "2"
unicode-width = "0.1.8"
clipboard = "0.5.0"
crossterm  = {version ="0.20.0", features = ["event-stream"]} 
serde = { version = "1.0.123", features = ["derive"] }
toml = "0.5.8"
cargo-deb = "1.28.3"
tokio = { version = "1.4.0", features = ["process", "macros", "rt-multi-thread"] }
tokio-util = { version = "0.6.3", features = ["codec"] }
futures = "0.3"
futures-util = "0.3.12"
once_cell = "1.5.2"
ropey="1.2.0"
syntect = "4.5"
chrono="0.4.19"
colors-transform = "0.2.11"
directories = "3.0.1"
regex = "1.4.3"
encoding_rs= "0.8.28"
byteorder = "1.4.3"
faccess = "0.2.3"
json5 = "0.3.0"
unicode-jp= "0.4.0"

[target.'cfg(windows)'.build-dependencies]
windres = "0.2.2"
