[package]
name = "ewin"
version = "0.8.5"
description = "Simple editor for Window(GUI) users."
authors = ["thinkingreed"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/thinkingreed/ewin"
license = "MIT"
keywords = ["cli", "editor"]
categories = ["command-line-utilities"]

[package.metadata.deb]
extended-description = """\
Simple editor for Window(GUI) users.\ 
There is no need to learn new operation commands.\
It provides basic features as a minimal text editor.\
depends = "$auto"\
"""
assets = [
    ["target/release/ewin", "usr/bin/ewin", "755"],
    ["README.md", "usr/share/doc/ewin/README", "644"],
]

[package.metadata.rpm]
package = "ewin"
[package.metadata.rpm.cargo]
buildflags = ["--release"]
[package.metadata.rpm.targets]
ewin = { path = "/usr/bin/ewin" }


[dependencies]
anyhow = "1"
termion = "1.5.5"
clap = "2"
unicode-width = "0"
clipboard = "0.5.0"
crossterm  = {version ="0.18.2", features = ["event-stream"]} 
serde = { version = "1.0.115", features = ["derive"] }
toml = "0.5.6"
cargo-deb = "1.28.0"
tokio = { version = "1.0.0", features = ["full"] }
tokio-util = { version = "0.6.0", features = ["codec"] }
futures = "0.3"
futures-util = "0.3.8"
once_cell = "1.5.2"
permissions = "0.2.0"
