[package]
name = "ewin"
version = "0.1.0"
authors = ["thinkingreed"]
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
anyhow = "1"
termion = "1.5.5"
clap = "2"
unicode-width = "0"
clipboard = "0.5.0"
crossterm  = "0.17.8" 
serde = { version = "1.0.115", features = ["derive"] }
toml = "0.5.6"
signal-hook = "0.1"
