[package]
name = "ewin"
version = "0.5.1"
description = "Simple editor for Winodws users."
authors = ["thinkingreed"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/thinkingreed/ewin"
license = "MIT"

[package.metadata.deb]
extended-description = """\
Simple editor for Winodws users.\ 
There is no need to learn new operation commands.\
It provides basic features as a minimal text editor.\
"""
assets = [
    ["target/release/ewin", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/ewin/README", "644"],
]

[dependencies]
anyhow = "1"
termion = "1.5.5"
clap = "2"
unicode-width = "0"
clipboard = "0.5.0"
crossterm  = "0.18.1" 
serde = { version = "1.0.115", features = ["derive"] }
toml = "0.5.6"
signal-hook = "0.1"
cargo-deb = "1.28.0"