[general.log] # option
# "info" or "debug" or "error"
level = "debug"

[general.editor.tab]
size = 4
# tab or half_width_blank
tab_input_type = "tab"

[general.editor.search]
case_sens = true
regex = false

[general.editor.format]
# tab or half_width_blank
indent_type = "half_width_blank"
# Valid only for half_width_blank
indent_size = 2

[general.prompt.open_file]
# Valid only for Windows
# "" is Not set or "current_directory"
directory_init_value = ""

# context menu
[general.ctx_menu]
content = """
{
  "editor": {
    "range_selected": [
      {"cut": []},
      {"copy": []},
      {"paste": []},
      {"convert": ["to_uppercase", "to_lowercase", "to_full_width", "to_half_width", "to_space", "to_tab"]},
      {"format": ["json", "xml", "html"]},
      {"macros": ["insertString.js", "switch_upper_lower.js"]}
    ],
    "range_non_selected": [
      {"paste": []},
      {"all_select": []},
      {"macros": ["insertString.js"]}
    ]
  },
  "header_bar": {
    "": [
      {"close": []},
      {"close_other_than_this_tab": []}
    ]
  }
}
"""

# If theme is set, theme color has the highest priority
[colors.theme] # option
# theme_path = "tmTheme.tmTheme"
# theme_background_enable = true
disable_syntax_highlight_ext = ["txt", "log"] 

[colors.editor]
background = "#000000"
foreground = "#ffffff"

[colors.editor.line_number]
background = "#505050"
foreground = "#c0c0c0"

[colors.editor.selection]
background = "#ff4500"
foreground = "#000000"

[colors.editor.search]
background = "#aa6400"
foreground = "#000000"

[colors.editor.control_char]
foreground = "#6e6e6e"

[colors.header_bar]
foreground = "#c0c0c0"

[colors.status_bar]
foreground = "#c0c0c0"

[colors.ctx_menu]
background_non_select = "#969696"
background_select = "#6495ed"
foreground_non_select = "#000000"
foreground_select = "#ffffff"

[colors.msg]
normal_foreground = "#ffffff"
highlight_foreground = "#00c800"
warning_foreground = "#aa6400"
err_foreground = "#ff0000"

[colors.file]
normal_foreground = "#c0c0c0"
directory_foreground = "#1e90ff"
executable_foreground = "#00c800"
