[general.editor.tab]
width = 4
[general.editor.search]
case_sens = true
regex = false
[colors.theme]

[colors.editor]
background = "#000000"
foreground = "#ffffff"

[colors.editor.line_number]
background = "#282828"
foreground = "#c0c0c0"

[colors.editor.selection]
background = "#dd4814"
foreground = "#000000"

[colors.editor.search]
background = "#dd4814"
foreground = "#000000"

[colors.editor.control_char]
foreground = "#6e6e6e"

[colors.header_bar]
foreground = "#c0c0c0"

[colors.status_bar]
foreground = "#c0c0c0"

[colors.msg]
normal_foreground = "#ffffff"
highlight_foreground = "#00c800"
warning_foreground = "#aa6400"
err_foreground = "#ff0000"
