name: ewin # you probably want to 'snapcraft register <name>'
version: &version "latest" # just for humans, typically '1.2+git' or '1.3.2'
base: core18 # the base snap is the execution environment for this snap
license: MIT
summary: Simple editor for Windows user # 79 char long summary
description: |
  Simple editor for Winodws users.
  There is no need to learn new operation commands.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  ewin:
    command: bin/ew

architectures:
  - build-on: amd64
  - build-on: arm64
  #- build-on: armhf

parts:
  ewin:
    source: https://github.com/thinkingreed/ewin.git
    source-tag: master
    plugin: rust
    stage-packages:
      - xorg-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
