pub const LANG_CONFIG: &'static str = r#"
[ja]
row = "行"
col = "列"
yes = "はい"
no = "いいえ"
with = "含む"
without = "含まない"
cancel = "キャンセル"
close = "閉じる"
fixed = "確定"
end = "終了"
save = "保存"
copy = "コピー"
paste = "ペースト"
undo = "元に戻す"
redo = "再実行"
cut = "切取"
changed = "変更済み"
detail = "詳細"
grep = "grep"
open = "開く"
movement = "移動"
file = "ファイル"
edit_search = "編集/検索"
convert = "変換"
filenm = "ファイル名"
file_list = "ファイル一覧"
presence_or_absence = "有無"
method_of_applying = "適用方法"
file_reload = "ファイル再読込"
keep_and_apply_string = "文字列を維持して適用"
range_select = "範囲選択"
mouse_switch = "マウス動作切替"
all_select = "全選択"
move_row = "行移動"
search = "検索"
search_bottom = "下部検索"
search_top = "上部検索"
search_str = "検索文字"
search_file = "検索ファイル"
search_folder = "検索フォルダ"
searching = "検索中..."
case_sens = "大/小文字区別"
regex = "正規表現"
new_file = "新ファイル"
move_setting_location = "設定箇所移動"
replace = "置換"
all_replace = "全置換"
select = "選択"
replace_char = "置換文字"
complement = "補完"
unable_to_edit = "編集不可"
key_record_start_stop = "記録開始終了"
key_record_exec = "記録実行"
key_recording = "操作記録中..."
help = "Help"
candidate_change = "候補変更"
encoding = "エンコーディング"
new_line_code = "改行コード"

# menu
menu = "メニュー"   
contents = "内容"
menu_select = "選択"

create_new = "新規作成"
save_as = "別名保存"
encode = "エンコード" 
end_of_all_save = "全保存終了" 
to_uppercase = ">大文字"
to_lowercase = ">小文字"
to_half_width = ">半角"
to_full_width = ">全角"
to_space  = "Tab > 半角空白"
to_tab = "半角空白 > Tab"
column_select_mode= "列選択モード"

## Msg ##
save_confirmation_to_close = "保存して終了しますか？"
terminal_size_small = "ターミナルサイズが小さい為に終了します。サイズを大きくして再実行して下さい"
set_new_filenm = "新規に作成するファイル名を入力して下さい"
set_open_filenm = "新規に開くファイル名を入力して下さい"
set_search = "検索する文字を入力して下さい"
set_replace = "検索する文字と置換する文字を入力して下さい"
set_grep = "検索する文字と検索するファイル、検索するフォルダを入力して下さい"
set_move_row = "移動する行番号を半角数字で入力して下さい"
set_enc_nl = "変更するエンコーディング・改行コード・BOMを設定して下さい"
selectable_only_for_utf8 = "UTF8の場合のみ選択可能"
move_to_specified_row = "指定行に移動"
open_target_file = "対象のファイルを開く"
not_entered_filenm = "ファイル名が入力されていません"
not_entered_search_str = "検索する文字が入力されていません"
not_entered_search_file = "検索するファイルが入力されていません"
not_entered_search_folder = "検索するフォルダが入力されていません"
not_entered_replace_str = "置換する文字が入力されていません"
not_entered_row_number_to_move = "移動する行番号が入力されていません"
cannot_find_char_search_for = "検索する文字が見つかりません"
long_time_to_search = "検索対象ファイル多い場合に非常に時間がかかる場合があります"
show_search_result = "検索結果を表示しています"
show_search_no_result = "検索対象は1件も存在しませんでした"
no_undo_operation = "元に戻す操作はありません"
no_redo_operation = "再実行する操作はありません"
number_within_current_number_of_rows = "現在の行数内の数字を入力して下さい"
cannot_convert_encoding = "一部の文字が変換出来ませんので、エンコーディングを変更するか、UTF8で保存して下さい"
select_menu = "メニューを選択して下さい"
processing_canceled = "処理がキャンセルされました"
# keybind
specification_err_key = "keyの指定に誤りがあります"
specification_err_keycmd = "cmdの指定に誤りがあります"
specification_err_keywhen = "whenの指定に誤りがあります"

# file
no_read_permission = "読込権限がありません"
no_write_permission = "書込権限無し"
file_opening_problem = "ファイルを開く際に問題が発生しました"
file_saving_problem = "ファイル保存時に問題が発生しました"
file_not_found = "ファイルが存在しません"
file_loading_failed = "ファイルの読込に失敗しました"
file_parsing_failed = "ファイルの解析に失敗しました"
log_file_create_failed = "ログファイルを作成できませんでした"
file_already_exists = "既に存在するファイル名です"
no_sel_range = "範囲を指定して下さい"
no_value_in_clipboard = "クリップボードに値はありません"
cannot_paste_multi_rows = "複数行を貼り付けることは出来ません"
no_key_record_exec = "実行する操作記録はありません"
unsupported_operation = "サポートされていない操作です"
increase_height_width_terminal = "ターミナルの高さ・幅を広げて下さい"

## editor info
simple_help_desc = "簡易ヘルプ: F1"
detailed_help_desc = "詳細ヘルプ: https://github.com/thinkingreed/ewin"

[en]
row = "row"
col = "col"
yes = "yes"
no = "no"
with = "With"
without = "Without"
cancel = "cancel"
close = "close"
fixed = "fixed"
end = "end"
save = "save"
copy = "copy"
paste = "paste"
undo = "undo"
redo = "redo"
cut = "cut"
changed = "changed"
detail = "detail"
grep = "grep"
open = "open"
movement = "move"
file = "file"
edit_search = "edit・search"
convert = "convert"
filenm = "filenm"
file_list = "file list"
presence_or_absence = "presence or absence"
method_of_applying = "method of applying"
file_reload = "file reload"
keep_and_apply_string = "Keep and apply string"
range_select = "range select"
mouse_switch = "mouse switch"
all_select = "all select"
move_row = "move row"
search = "search"
search_bottom = "bottom search"
search_top = "top search"
search_str = "search character"
search_file = "search file"
search_folder = "search folder"
searching = "searching..."
case_sens = "case sens"
regex = "regex"
new_file = "new file"
move_setting_location = "move setting location"
replace = "replace"
all_replace = "all replace"
select = "select"
replace_char = "replace character"
complement = "complement"
unable_to_edit = "unable to edit"
key_record_start_stop = "rec start/stop"
key_record_exec = "rec exec"
key_recording = "operation recording..."
help = "help"
candidate_change = "candidate change"
encoding = "encoding"
new_line_code = "new line code"

# Menu
menu = "menu"
contents = "contents"
menu_select = "select"

create_new = "create new"
save_as = "save as"
encode = "encode" 
end_of_all_save = "end of all save" 
column_select_mode= "column select mode"


to_uppercase = "to Uppercase"
to_lowercase = "to Lowercase"
to_half_width = "to Half width"
to_full_width = ">to Full width"
to_space = "Tab > Space"
to_tab = "Space > Tab"

## Msg ##
save_confirmation_to_close = "Do you want to save and exit?"
terminal_size_small = "It will end because the terminal size is small. Please increase the size and try again"
set_new_filenm = "Enter the name of the newly created file"
set_open_filenm = "Enter the name of the newly opened file"
set_search = "Enter the characters you want to search for"
set_replace = "Enter the character to search for and the character to replace"
set_grep = "Enter the characters to search, the files to search, and the folder to search"
set_move_row = "Enter the line number to move in half width numbers"
set_enc_nl = "Set the encoding・new line code・BOM to be changed"
selectable_only_for_utf8 = "Selectable only for UTF8"
move_to_specified_row = "move to specified line"
open_target_file = "open target file in another terminal"
not_entered_filenm = "File name is not entered"
not_entered_search_str = "Search charctor is not entered"
not_entered_search_file = "Search file is not entered"
not_entered_search_folder = "Search folder is not entered"
not_entered_replace_str = "Replace charctor is not entered"
not_entered_row_number_to_move = "Line number to move is not entered "
cannot_find_char_search_for = "Cannot find the character to search for"
long_time_to_search = "It may take a long time if there are many files to be searched"
show_search_result = "show search result"
show_search_no_result = "There was no search target"
no_undo_operation = "There is no undo operation"
no_redo_operation = "There is no operation redo"
number_within_current_number_of_rows = "Enter a number within the current number of lines"
cannot_convert_encoding = "Some characters cannot be converted, so please change the encoding or save in UTF8"
select_menu = "Please select menu"
processing_canceled = "Please select menu"

# keybind
specification_err_key = "There is an error in the Key specification"
specification_err_keycmd = "There is an error in the cmd specification"
specification_err_keywhen = "There is an error in the when specification"

# file
no_read_permission = "No read permission"
no_write_permission = "No write permission"
file_opening_problem = "There was a problem in opening the file"
file_saving_problem = "There was a problem saving the file"
file_not_found = "File not found"
file_loading_failed = "file loading failed"
file_parsing_failed = "file parsing failed"
file_already_exists = "file already exists"
log_file_create_failed = "log file create failed"
no_sel_range = "Please specify the copy range"
no_value_in_clipboard = "There is no value in the clipboard"
cannot_paste_multi_rows = "Can not paste multilines"
no_key_record_exec = "There is no operation record to be executed"
unsupported_operation = "This is an unsupported operation"
increase_height_width_terminal = "Increase the height・width of the terminal"

## editor info
simple_help_desc = "Simple help: F1"
detailed_help_desc = "Detailed help: https://github.com/thinkingreed/ewin"

"#;
