[package]
name = "ewin-term"
version = "0.0.2"
rust-version = "1.56.0"
description = "Simple editor for Window(GUI) users.No need to remember commands."
authors = ["thinkingreed"]
edition = "2021"
repository = "https://github.com/thinkingreed/ewin"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
crossterm  = {version ="0.22.1", features = ["event-stream"]} 
tokio = { version = "1.4.0", features = ["process", "macros", "rt-multi-thread"] }
tokio-util = { version = "0.6.3", features = ["codec"] }
once_cell = "1.5.2"
unicode-width = "0.1.8"
directories = "4.0.1"
rusty_v8= "0.28.0" # "0.32.1" compiles, but is rejected because it compiles every time.
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
futures-util = "0.3.12"
clap = "2.34.0"

ewin-com = {version = "0.0.2", path = "../ewin-com" }
ewin-editor = {version = "0.0.2", path = "../ewin-editor" }
ewin-prom = {version = "0.0.2", path = "../ewin-prom" }
