[editor]
#background = "#f4f5f7"
background = "#fafafa"
foreground = "#000000"

[editor.line_number]
active_background = "#ffffff"
active_foreground = "#000000"
passive_background = "#ffffff"
passive_foreground = "#c0c0c0"

[editor.selection]
background = "#2d5fff"
foreground = "#ffffff"

[editor.search]
background = "#ffff50"
foreground = "#000000"

[editor.control_char]
foreground = "#c0c0c0"

[editor.column_char_width_gap_space]
foreground = "#565656"
background = "#282828"

[editor.scrollbar]
horizontal_background = "#dedede"
vertical_background = "#dedede"

[editor.scale]
foreground = "#C4C4C4"
background = "#dedede"

[editor.window.split_line]
background = "#bebebe"

[system.btn]
foreground = "#000000"
background = "#c0c0c0"

[system.state]
foreground = "#000000"
background = "#c0c0c0"

[menubar]
active_foreground = "#000000"
active_background = "#a0a0a0"
passive_foreground = "#000000"
passive_background = "#dedede"
default_background = "#dedede"

[filebar]
active_foreground = "#ffffff"
active_background = "#333333"
passive_foreground = "#ffffff"
passive_background = "#c0c0c0"
default_background = "#dedede"

[statusbar]
foreground = "#c0c0c0"

[ctx_menu]
non_select_background = "#c0c0c0"
select_background = "#6495ed"
non_select_foreground = "#000000"
select_foreground = "#ffffff"

[dialog]
default_foreground = "#000000"
default_background = "#dedede"
header_foreground = "#ffffff"
header_background = "#787878"
select_background = "#6495ed"

[msg]
normal_foreground = "#000000"
highlight_foreground = "#00c800"
warning_foreground = "#aa6400"
err_foreground = "#ff0000"

[file]
normal_foreground = "#c0c0c0"
directory_foreground = "#1e90ff"
executable_foreground = "#00c800"
