# If theme is set, theme color has the highest priority
[theme] # option
# highlight_theme_path = "tmTheme.tmTheme"
# highlight_theme_background_enable = true
disable_highlight_ext = ["txt", "log"]

# Only files below this value will be highlighted(positive number:MByte)
disable_syntax_highlight_file_size = 3
# "black" or "white"
default_color_theme = "white"

[editor]
background = "#000000"
foreground = "#ffffff"

[editor.line_number]
active_background = "#000000"
active_foreground = "#ffffff"
passive_background = "#505050"
passive_foreground = "#c0c0c0"

[editor.selection]
background = "#ff4500"
foreground = "#000000"

[editor.search]
background = "#aa6400"
foreground = "#000000"

[editor.control_char]
foreground = "#6e6e6e"

[editor.column_char_width_gap_space]
foreground = "#a9a9a9"
background = "#d7d7d7"

[editor.scale]
foreground = "#444444"
background = "#212121"

[editor.window.split_line]
background = "#414141"

[system.btn]
foreground = "#000000"
background = "#c0c0c0"

[system.state]
foreground = "#000000"
background = "#c0c0c0"

[system.scrollbar]
horizontal_background = "#212121"
vertical_background = "#212121"

[menubar]
active_foreground = "#ffffff"
active_background = "#5f5f5f"
passive_foreground = "#ffffff"
passive_background = "#212121"
default_background = "#212121"

[filebar]
active_foreground = "#000000"
active_background = "#c0c0c0"
passive_foreground = "#000000"
passive_background = "#6e6e6e"
default_background = "#212121"


[statusbar]
foreground = "#c0c0c0"
background = "#282828"

[ctx_menu]
non_select_background = "#969696"
select_background = "#6495ed"
non_select_foreground = "#000000"
select_foreground = "#ffffff"

[dialog]
default_foreground = "#ffffff"
default_background = "#212121"
header_foreground = "#000000"
header_background = "#878787"

[msg]
normal_foreground = "#ffffff"
highlight_foreground = "#00c800"
warning_foreground = "#aa6400"
err_foreground = "#ff0000"
background = "#282828"

[file]
normal_foreground = "#c0c0c0"
directory_foreground = "#1e90ff"
executable_foreground = "#00c800"

[sidebar]
background = "#000000"
foreground = "#ffffff"
header_background = "#212121"