row = "行"
col = "列"
yes = "はい"
no = "いいえ"
with = "含む"
without = "含まない"
cancel = "キャンセル"
close = "閉じる"
fixed = "確定"
end = "終了"
save = "保存"
save_forced = "強制保存"
copy = "コピー"
paste = "貼り付け"
undo = "元に戻す"
redo = "再実行"
cut = "切り取り"
changed = "変更済み"
detail = "詳細"
grep = "grep"
open_file = "開く"
reopen = "開き直す"
movement = "移動"
file = "ファイル"
edit = "編集"
unable_to_edit = "編集不可"
edit_discard = "編集破棄"
convert = "変換"
filenm = "ファイル名"
file_list = "ファイル一覧"
presence_or_absence = "有無"
method_of_apply = "適用方法"
file_reload = "ファイル再読込"
keep_and_apply_string = "文字列を維持して適用"
range_select = "範囲選択"
mouse_switch = "マウス有効無効切替"
mouse_disable = "マウス無効"
all_select = "全選択"
move_row = "行移動"
format = "フォーマット"
search = "検索"
search_bottom = "下部検索"
search_top = "上部検索"
search_str = "検索文字"
search_file = "検索ファイル"
search_folder = "検索フォルダ"
searching = "検索中..."
case_sens = "大/小文字区別"
regex = "正規表現"
new_file = "新ファイル"
move_setting_location = "設定箇所移動"
replace = "置換"
all_replace = "全置換"
select = "選択"
replace_str = "置換文字"
complement = "補完"
key_record_start_stop = "記録開始終了"
key_record_exec = "記録実行"
key_recording = "操作記録中..."
help = "Help"
candidate_change = "候補変更"
encoding = "エンコーディング"
new_line_code = "改行コード"
none = "無し"
mouse_down_left = "クリック"
# menu
menu = "メニュー"   
contents = "内容"

create_new_file = "新規作成"
save_as = "別名保存"
encode = "エンコード" 
end_of_all_save = "全保存終了" 
to_uppercase = "大文字"
to_lowercase = "小文字"
to_half_width = "半角"
to_full_width = "全角"
to_space  = "Tab > 半角空白"
to_tab = "半角空白 > Tab"
html = "HTML"
xml = "XML"
json = "JSON"
json5 = "JSON5"
toml = "TOML"

box_select = "Box選択"
box_insert = "Box挿入"
box_select_mode = "Box選択モード"
macros = "マクロ"

display = "表示"
row_no = "行番号"
scale = "目盛り"

## Msg ##
save_confirm_to_close = "保存して終了しますか？"
terminal_size_small = "ターミナルサイズを大きくして再実行して下さい"
set_new_filenm = "新規に作成するファイル名を入力して下さい"
set_open_filenm = "新規に開くファイル名を入力して下さい"
set_exec_mocro_filenm = "実行するマクロファイル名を入力して下さい"
set_search = "検索する文字を入力して下さい"
set_replace = "検索する文字と置換する文字を入力して下さい"
set_grep = "検索する文字と検索するファイル、検索するフォルダを入力して下さい"
set_move_row = "移動する行番号を半角数字で入力して下さい"
set_enc_nl = "変更するエンコーディング・改行コード・BOMを設定して下さい"
selectable_only_for_utf8 = "UTF8の場合のみ選択可能"
move_to_specified_row = "指定行に移動"
open_target_file = "対象のファイルを開く"
not_entered_filenm = "ファイル名が入力されていません"
not_set_search_str = "検索する文字が設定されていません"
not_entered_search_file = "検索するファイルが入力されていません"
not_entered_search_folder = "検索するフォルダが入力されていません"
not_entered_replace_str = "置換する文字が入力されていません"
not_entered_row_number_to_move = "移動する行番号が入力されていません"
cannot_find_search_char = "検索する文字が見つかりません"
long_time_to_search = "検索対象ファイル多い場合に非常に時間がかかる場合があります"
show_search_result = "検索結果を表示しています"
show_search_no_result = "検索対象は1件も存在しませんでした"
no_undo_operation = "元に戻す操作はありません"
no_redo_operation = "再実行する操作はありません"
number_within_current_number_of_rows = "現在の行数内の数字を入力して下さい"
writing_cannot_convert_encoding = "一部の文字が変換出来ませんので、エンコーディングを変更するか、UTF8で保存して下さい"
reading_cannot_convert_encoding = "一部の文字が変換出来ませんので、エンコーディングを変更して下さい"
select_menu = "メニューを選択して下さい"
processing_canceled = "処理がキャンセルされました"
parsing_failed = "解析に失敗しました"
# keybind
specification_err_key = "keyの指定に誤りがあります"
specification_err_keycmd = "cmdの指定に誤りがあります"
specification_err_keywhen = "whenの指定に誤りがあります"

# file
no_read_permission = "読込権限がありません"
no_write_permission = "書込権限無し"
file_opening_problem = "ファイルを開く際に問題が発生しました"
file_saving_problem = "ファイル保存時に問題が発生しました"
file_not_found = "ファイルが存在しません"
file_loading_failed = "ファイルの読込に失敗しました"
file_parsing_failed = "ファイルの解析に失敗しました"
log_file_create_failed = "ログファイルを作成出来ませんでした"
check_log_file = "ログファイルを確認下さい"
file_already_exists = "既に存在するファイル名です"
no_sel_range = "範囲を指定して下さい"
no_value_in_clipboard = "クリップボードに値はありません"
cannot_paste_multi_rows = "複数行を貼り付けることは出来ません"
no_key_record_exec = "実行する操作記録はありません"
unsupported_operation = "サポートされていない操作です"
increase_height_width_terminal = "ターミナルの高さ・幅を広げて下さい"
close_other_than_this_tab = "このタブ以外を閉じる"
no_tab_can_be_switched = "切り替えられるタブはありません"
file_has_been_modified_by_other_app = "ファイルは他のアプリケーションによって変更されています"
open_modified_time = "Open時更新時間"
last_modified_time = "最終更新時間"
not_edited_will_reloaded_auto = "以後、未編集時は自動で再読込"
no_further_monitoring = "以後、監視しない"
extension = "拡張子"

## editor info
simple_help_desc = "簡易ヘルプ: F1"
detailed_help_desc = "詳細ヘルプ: https://github.com/thinkingreed/ewin"
## macro
script_run_error = "Script 実行時エラー"
script_compile_error = "Script 構文エラー"
specify_file_and_exec_macro = "ファイル指定してマクロ実行"
## input comple
no_input_comple_candidates = "入力補完候補がありません"
