[package]
name = "ewin-const"
publish = false
authors.workspace = true
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
encoding_rs.workspace = true
once_cell.workspace = true
crossterm.workspace = true