row = "row"
col = "col"
yes = "yes"
no = "no"
with = "With"
without = "Without"
cancel = "cancel"
close = "close"
fixed = "fixed"
end = "end"
save = "save"
save_forced = "save forced"
copy = "copy"
paste = "paste"
undo = "undo"
redo = "redo"
cut = "cut"
changed = "changed"
detail = "detail"
grep = "grep"
open = "open"
reopen = "reopen"
movement = "move"
file = "file"
edit = "edit"
unable_to_edit = "unable to edit"
edit_discard = "edit discard"
convert = "convert"
filenm = "filenm"
file_list = "file list"
presence_or_absence = "presence or absence"
method_of_applying = "method of applying"
file_reload = "file reload"
keep_and_apply_string = "Keep and apply string"
range_select = "range select"
mouse_switch = "mouse switch"
all_select = "all select"
move_row = "move row"
format = "format"
search = "search"
search_bottom = "bottom search"
search_top = "top search"
search_str = "search character"
search_file = "search file"
search_folder = "search folder"
searching = "searching..."
case_sens = "case sens"
regex = "regex"
new_file = "new file"
move_setting_location = "move setting location"
replace = "replace"
all_replace = "all replace"
select = "select"
replace_char = "replace character"
complement = "complement"
key_record_start_stop = "rec start/stop"
key_record_exec = "rec exec"
key_recording = "operation recording..."
help = "help"
candidate_change = "candidate change"
encoding = "encoding"
new_line_code = "new line code"

# Menu
menu = "menu"
contents = "contents"

create_new = "create new"
save_as = "save as"
encode = "encode" 
end_of_all_save = "end of all save"
box_select = "box select"
box_insert = "box insert"
box_select_mode= "box select mode"
macros = "macro"

to_uppercase = "Uppercase"
to_lowercase = "Lowercase"
to_half_width = "Half width"
to_full_width = "Full width"
to_space = "Tab > Space"
to_tab = "Space > Tab"
html = "HTML"
xml = "XML"
json = "JSON"
json5 = "JSON5"
toml = "TOML"


## Msg ##
save_confirm_to_close = "Do you want to save and exit?"
terminal_size_small = "Please increase the terminal size and try again"
set_new_filenm = "Enter the name of the newly created file"
set_open_filenm = "Enter the name of the newly opened file"
set_exec_mocro_filenm = "Enter the name of the execute macro file"
set_search = "Enter the characters you want to search for"
set_replace = "Enter the character to search for and the character to replace"
set_grep = "Enter the characters to search, the files to search, and the folder to search"
set_move_row = "Enter the line number to move in half width numbers"
set_enc_nl = "Set the encoding・new line code・BOM to be changed"
selectable_only_for_utf8 = "Selectable only for UTF8"
move_to_specified_row = "move to specified line"
open_target_file = "open target file"
not_entered_filenm = "File name is not entered"
not_entered_search_str = "Search charctor is not entered"
not_entered_search_file = "Search file is not entered"
not_entered_search_folder = "Search folder is not entered"
not_entered_replace_str = "Replace charctor is not entered"
not_entered_row_number_to_move = "Line number to move is not entered "
cannot_find_char_search_for = "Cannot find the character to search for"
long_time_to_search = "It may take a long time if there are many files to be searched"
show_search_result = "show search result"
show_search_no_result = "There was no search target"
no_undo_operation = "There is no undo operation"
no_redo_operation = "There is no operation redo"
number_within_current_number_of_rows = "Enter a number within the current number of lines"
cannot_convert_encoding = "Some characters cannot be converted, so please change the encoding or save in UTF8"
select_menu = "Please select menu"
processing_canceled = "Please select menu"
parsing_failed = "parsing failed"

# keybind
specification_err_key = "There is an error in the Key specification"
specification_err_keycmd = "There is an error in the cmd specification"
specification_err_keywhen = "There is an error in the when specification"

# file
no_read_permission = "No read permission"
no_write_permission = "No write permission"
file_opening_problem = "There was a problem in opening the file"
file_saving_problem = "There was a problem saving the file"
file_not_found = "File not found"
file_loading_failed = "file loading failed"
file_parsing_failed = "file parsing failed"
file_already_exists = "file already exists"
log_file_create_failed = "log file create failed"
check_log_file = "check log file"
no_sel_range = "Please specify the copy range"
no_value_in_clipboard = "There is no value in the clipboard"
cannot_paste_multi_rows = "Can not paste multilines"
no_key_record_exec = "There is no operation record to be executed"
unsupported_operation = "This is an unsupported operation"
increase_height_width_terminal = "Increase the height・width of the terminal"
close_other_than_this_tab = "Close other than this tab"
no_tab_can_be_switched = "No tab that can be switched"
file_has_been_modified = "File has been modified"
file_has_been_modified_by_other_app = "file has been modified by other application"
open_modified_time = "Modified time when opened "
last_modified_time = "Last update time"
not_edited_will_reloaded_auto = "After that, if it is not edited, it will be reloaded auto"
no_further_monitoring = "No further monitoring"
auto_assigned_extension = "Auto assigned extension"

## macro
script_run_error = "script run error"
script_compile_error = "script syntax error"
specify_file_and_exec_macro = "specify_file_and_exec_macro"

## editor info
simple_help_desc = "Simple help: F1"
detailed_help_desc = "Detailed help: https://github.com/thinkingreed/ewin"

