name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt install build-essential 
          sudo apt install xorg-dev
          sudo apt install libxcb-render0-dev
          sudo apt install libxcb-shape0-dev
          sudo apt install libxcb-xfixes0-dev
          cargo build --verbose
      #      - name: clippy
      #        with:
      #          command: clippy
      #          args: -- -D warnings
      - name: Run tests
        run: cargo test --verbose
